Python For Data Analysis

Capitulo 4: Numpy

In [2]:
# Importamos la librería numpy
import numpy as np

La principal herramientas del Numpy en ndarray un array n-vectorial rápido y eficiente en memoria, 

Carácteristicas del ndarray:

Forma : data.shape devuelve la forma del Array
Tipo : data.dtype
Numero de dimensiones: data.ndim

Vamos a ver como se crea un array

In [6]:
# A partir de una lista

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [8]:
#Vamos a ver si forma 
arr1.shape

(5,)

In [9]:
#Vamos a ver su tipo
arr1.dtype

dtype('float64')

In [10]:
# A partir de una lista multdimensional
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
#Vamos a ver si forma 
arr2.shape

(2, 4)

In [13]:
#Vamos a ver cuantas dimensiones tiene
arr2.ndim

2

Se puede inicializar los arrays a zero, unos, con un rango de valores o un grupo de valores no definidos

In [28]:
# Inicializar los arrays a 0
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [29]:
# Incializar los arrays a 1
np.ones(3)

array([ 1.,  1.,  1.])

In [30]:
# Sin valores predefinidos 
np.empty((2,3,2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [31]:
# En un rango de valores 
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Hay otra funciones para crear arrays asarray, zeros_likes, one_likes, empty_like son similares a la basica pero copian las carácteristicas de otro array. Además de eye o identity para crear la identidad.


In [32]:
# Matriz  Identidad de 5
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

Cuando se crea un array se puede especificar el tipo 
Tipos disponibles:
int8, uint8, int16, uint16, int32, uint32,int64, uint64,float16,float32,float64, float128,float128 
complex64, complex128, complex256, bool, object, string_ ,unicode_  

In [33]:
# Se crea una array de tipo entero
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [36]:
# Se puede convertir los arrays de un tipo a otro con la funcion astype
f_arr2 = arr2.astype(np.float64)
f_arr2.dtype

dtype('float64')

In [40]:
# Tambien los podemos usar para transformar texto a númerico
astr = np.array(('2','3.5', '6.3'), dtype=np.string_)
astr.dtype

dtype('S3')

In [44]:
astr = astr.astype(np.float64)
astr.dtype

dtype('float64')

In [45]:
astr

array([ 2. ,  3.5,  6.3])

In [4]:
# se puede crear arrays empty especificando el tipo 
np.empty(5, dtype=np.string_)

array(['(', '\x18', 'k', '\x92', 'w'], 
      dtype='|S1')

La vectorización consiste en realizar operaciones sin realizar bucles for. Si operas dos ndaarrys del mismo tamaño con cualquier operador, operara cada elemento con su par. Si operas un ndarray con un escalar operará todos los elementos de ndarray con el escalar. Ejemplos:

In [47]:
arr1 = np.arange(11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr1 * arr1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [49]:
arr1 + arr1 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
arr1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
arr1 ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

La indexación y el slicing es muy rico en numpy, la indexaciones son muy sencillas en los array de una dimensión 

In [10]:
# Definimos un array unidimensional
arr = np.arange(10) + 3
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
# Seleccionar un elemento de un array 
arr[5]

8

In [11]:
# Seleciona la posiciones de la 5 a las 7 (Recuerda que los array empiezan en cero)
arr[5:8]

array([ 8,  9, 10])

Una de la cosas importante es una vez seleccionado un slice se puede asignar valores directamente

In [12]:
# Los 3 primeros valores los queremos poner a cero 

arr[0:3] = 0
arr

array([ 0,  0,  0,  6,  7,  8,  9, 10, 11, 12])

Como se observa los cambión se propagan por la slice, tambien es importante que los datos no se copian cualquier modificación de la vista (slice / subconjunto) afecta al recurso original

In [13]:
# Creamos una sub array con los 3 primeros elementos
arr_slice=arr[0:3]
arr_slice

array([0, 0, 0])

In [16]:
#Al sub array le modificamos la primera posición
arr_slice[0] = 1
arr_slice

array([1, 0, 0])

In [17]:
# Si mostramos el array original se observa que el cambio hehco en el arr_slice se afecta al array original
arr

array([ 1,  0,  0,  6,  7,  8,  9, 10, 11, 12])

Con los arrays multidimensionales tenemos mas posbilidades

In [19]:
# Definimos un arrray multidimensional 
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Si seleccionamos un elemento arr2d[x] le reducimos una dimensión
arr2d[1]

array([4, 5, 6])

In [21]:
# Para especificar un único elemento hay que especificar todas la dimensiones de array
arr2d[0][0]

1

In [22]:
# O tambien
arr2d[0,0]

1

In [23]:
# Se puede indenzar los array con la sintaxis de rangos de Python (:)
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [24]:
# Otro ejemplo , devuelve un objeto de 2 dimensiones (3,1)
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [25]:
# En cambio esta notación devuelve un array unidimensional
arr2d[:, 0]

array([1, 4, 7])

Indexación Boleana podemos pasar un vector boleano con indexación y seleccionara los registros que sean TRUE

In [3]:
# Generamos un array de nombres y una array de numeros aleatorios
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
from numpy.random import randn
data = randn( 7 , 4 ) 
data

array([[ 0.22771466, -0.12440328, -0.28949651, -0.73946482],
       [-0.15430186, -2.01777887,  0.73293146, -1.00990067],
       [ 0.18661425, -1.05703212, -0.60106148,  2.71567855],
       [-1.47245708, -0.25656885,  1.53483321, -0.99867219],
       [-0.55253389,  0.87614064, -0.2470567 ,  0.55099038],
       [ 0.25919939,  1.21079625, -0.39659825, -0.92843003],
       [ 0.12039099, -1.11561077,  1.26876689,  1.0593982 ]])

In [32]:
# Generamos un array boleano
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [34]:
#Pasamos este array booleano al array Data como indexación
data[names == 'Bob']

array([[ 0.20079523,  1.88068943, -0.26552257,  0.26768185],
       [ 0.17762119,  1.50077559, -0.11463791,  1.08267002]])

In [35]:
#Podemos seguir añadiendo opciones de indexacion 
data[names == 'Bob',:2]

array([[ 0.20079523,  1.88068943],
       [ 0.17762119,  1.50077559]])

In [37]:
# Obtendriamos el vector contrario 
data[names!='Bob']

array([[ 0.67758465,  0.6067688 , -0.54960465, -0.3486551 ],
       [-0.1742294 , -0.06446678, -0.31683177,  1.88719201],
       [-0.24752747,  0.77685846, -1.01379302,  1.61245942],
       [ 0.92786437,  0.22729571, -1.14933555,  2.30601103],
       [-0.69247914,  0.56667263, -1.07065   , -0.40595594]])

In [38]:
# sería los mismo que expresar
data[-(names=='Bob')]

array([[ 0.67758465,  0.6067688 , -0.54960465, -0.3486551 ],
       [-0.1742294 , -0.06446678, -0.31683177,  1.88719201],
       [-0.24752747,  0.77685846, -1.01379302,  1.61245942],
       [ 0.92786437,  0.22729571, -1.14933555,  2.30601103],
       [-0.69247914,  0.56667263, -1.07065   , -0.40595594]])

In [41]:
# Se pueden combinar los vector Booleanos mediante OR o and 
data[(names=='Bob') | (names=='Will') ]

array([[ 0.20079523,  1.88068943, -0.26552257,  0.26768185],
       [-0.1742294 , -0.06446678, -0.31683177,  1.88719201],
       [ 0.17762119,  1.50077559, -0.11463791,  1.08267002],
       [-0.24752747,  0.77685846, -1.01379302,  1.61245942]])

In [45]:
# Se puede poner cualquier tipo de condición, devuelve un array con los valores negativos
data[data < 0]

array([-0.26552257, -0.54960465, -0.3486551 , -0.1742294 , -0.06446678,
       -0.31683177, -0.11463791, -0.24752747, -1.01379302, -1.14933555,
       -0.69247914, -1.07065   , -0.40595594])

Fancy Indexing, permite obtener una selección y un orden de las filas pasando una lista de enteros,
el Fancy indexing crea una nueva copia del array.


In [4]:
# Generamos una matriz donde cada fila tiene como contenido su número de fila
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [5]:
# Seleccionamos la fila 4 primero, despues la 3 ..etc
arr[[4, 3, 0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [7]:
# Si se le pasan 2 listas hace una cosa diferente, generamos un array
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [8]:
# Vamos a pasarle 2 listas
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Lo que ha hecho es selecciona los pares (1,0) (5,3) (7,1) (2,2), vamos a probar con otras opciones


In [10]:
# En este caso se han seleccionado la filas 1,5,7,2 y re han reordenado la columnas de la forma 0,3,1,2
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [11]:
#Otra forma con la función np.ix_
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Transposing Arrays and Swapping Axes, veremos como cambar ejes y transponer matrices

In [13]:
#Generamos una ndarray bidimensional
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
#Con el sufijo .T obtenemos la transpuesta
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [17]:
# Para obtener multiplicar matrices se usa la función np.dot
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [20]:
# Tambien existe la fnción .transpose para realizar transposicionaes mas precisas (matrices cuadradas)
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [21]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [23]:
# Aparte de la transposicón .T existe la funcion swapaxes
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

Universal Functions (ufunc)
Son funciones que mejoran la capacidad de los ndarray

In [26]:
# Algunas afectan a cada elemento del ndarray, esta funciones son conocidas como unary ufunc
arr = np.arange(10)
np.sqrt(arr)


array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [33]:
# Otra aceptan 2 o más ndarrays de entrada (binary ufuncs) np.maximum que devuelve el máximo de cada lista
x = randn(8)
y = randn(8)
z = randn(8)
np.maximum(x, y, z) 

array([ 0.6668253 ,  1.41525423,  1.36459443, -0.41045999,  0.50670644,
       -0.15117266, -0.00457923, -0.66065827])

In [34]:
# Tambien puede devolver varios arrays como modf, que devuelve la parte entera y la fraccional en vectores diferentes
arr = randn(7) * 5
arr

array([-7.83535604,  2.28646542, -2.21237768,  5.39393283, -7.39863411,
       -1.95273611, -0.08489102])

In [35]:
np.modf(arr)

(array([-0.83535604,  0.28646542, -0.21237768,  0.39393283, -0.39863411,
        -0.95273611, -0.08489102]), array([-7.,  2., -2.,  5., -7., -1., -0.]))

Expressing Conditional Logic as Array Operations
la función np.where es la opción vectorizada de la sentencias if/else 

In [39]:
# Tenemos 3 arrays, 2 con datos y con booleano
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

# Podemos expresar con el if/else la siguiente cóndiciones
result = [( x if c else y)for x, y, c in zip(xarr, yarr, cond)]
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [40]:
# En vez de esto podemos usar la función np.where
result = np.where(cond, xarr, yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [41]:
# Los argumentos de np.where no tiene porque ser lista
arr = randn(4, 4)
arr

array([[-0.30169003,  0.02903044,  0.14158681, -0.46652591],
       [ 0.90050704, -0.86238434,  0.23692085,  1.04466733],
       [ 0.97909431, -0.47252243,  1.71636789, -1.25533306],
       [-0.98037554,  0.25883006, -0.42962412, -1.36374112]])

In [42]:
# Los valores positivos 2 y los valores negativos -2
np.where(arr > 0, 2, -2)

array([[-2,  2,  2, -2],
       [ 2, -2,  2,  2],
       [ 2, -2,  2, -2],
       [-2,  2, -2, -2]])

In [44]:
# Si solo queremos poner los valores positivos a 2
np.where(arr > 0, 2, arr) 

array([[-0.30169003,  2.        ,  2.        , -0.46652591],
       [ 2.        , -0.86238434,  2.        ,  2.        ],
       [ 2.        , -0.47252243,  2.        , -1.25533306],
       [-0.98037554,  2.        , -0.42962412, -1.36374112]])

Mathematical and Statistical Methods
En numpy existen una gran cantidad de funciones y metodos para realizar summarizaciones

In [5]:
# Generamos una ndarray bidimensional con números aleatorios
arr = np.random.randn(5, 4)
arr

array([[-1.1043292 ,  0.54687731, -0.61644323, -0.22310466],
       [ 0.42309496,  1.11175163, -1.80365247, -1.28791018],
       [ 0.27329882,  0.19456962,  1.03325955, -1.12990213],
       [ 0.33641422,  1.54061876,  1.24174622, -0.50824488],
       [ 1.05129485,  1.88512222, -1.21902183,  0.92971953]])

In [6]:
# Método para calcular la media del ndarray
arr.mean()

0.13375795595747569

In [7]:
# Función para calcular la media del ndarray
np.mean(arr)

0.13375795595747569

In [8]:
# Método para calcular la suma
arr.sum()

2.6751591191495141

In [9]:
# En los métodos se puede especificar los ejes
arr.mean(axis=1)

array([-0.34924995, -0.38917901,  0.09280646,  0.65263358,  0.66177869])

In [10]:
# Ahora la media por filas
arr.mean(0)

array([ 0.19595473,  1.05578791, -0.27282235, -0.44388846])

In [12]:
# Otros métodos como cumprod o cumsum no realizan agregaciones producen un array intermedio
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
# Método cumsum, hace la suma acumulado de la matriz original (En el ejemplo por filas)
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [16]:
# Método prod, hace el producto acumulado de la matriz original (En el ejemplo por columnas)
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [17]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

Methods for Boolean Arrays
Alguno ejemplos de metodos de los arrays booleanos

In [20]:
# sum permite sumar los True de array
arr = randn(100)
(arr > 0).sum()

50

In [21]:
# all chequea si todos los valores son True (operación AND entre todos los elementos)
bools = np.array([False, False, True, False])
bools.all()

False

In [22]:
# any chequea si al menos un valor es True (operación or entre todos los elementos)
bools.any()

True

Sorting
Los arrays tienen métodos para la ordenación

In [23]:
# Generamos un array
arr = randn(8)
arr

array([ 0.88929543,  0.06315569,  0.27353093, -0.47026012, -0.74732192,
        0.23193802,  0.20310593,  0.64421098])

In [26]:
# Ordenamos, el array original se vera modificado
arr.sort()
arr

array([-0.74732192, -0.47026012,  0.06315569,  0.20310593,  0.23193802,
        0.27353093,  0.64421098,  0.88929543])

In [27]:
# Vamos a verlo en arrays muldimensionales 
arr = randn(5, 3)
arr

array([[ 1.01083541, -0.08909137, -0.76610761],
       [-0.52747964,  0.70663223,  0.86999612],
       [-1.88582228, -0.68737011, -0.08320794],
       [-0.53497154,  0.81298276, -0.66410714],
       [ 0.17989514, -1.68594885, -0.40881117]])

In [28]:
# Ordenamos por columnas
arr.sort(1)
arr

array([[-0.76610761, -0.08909137,  1.01083541],
       [-0.52747964,  0.70663223,  0.86999612],
       [-1.88582228, -0.68737011, -0.08320794],
       [-0.66410714, -0.53497154,  0.81298276],
       [-1.68594885, -0.40881117,  0.17989514]])

In [29]:
# Si usáramos la función np.sort devuelve una copia ordenada
np.sort(arr)

array([[-0.76610761, -0.08909137,  1.01083541],
       [-0.52747964,  0.70663223,  0.86999612],
       [-1.88582228, -0.68737011, -0.08320794],
       [-0.66410714, -0.53497154,  0.81298276],
       [-1.68594885, -0.40881117,  0.17989514]])

Unique and Other Set Logic
Numpy tiene funciones para lo array 1 dimensionales para operaciones de conjuntos

In [30]:
# La función Unique 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='|S4')

In [31]:
# Otra función importante es la función que chequea un array contra un conjunto de valores
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

Storing Arrays on Disk in Binary Format
Numpy permite guardar archivos binarios no comprimidos con extensión numpy
Tener en cuenta que se pueden guardar varios arrays en un archivo comprimido

In [33]:
arr = np.arange(10)
np.save('some_array', arr)
np.load('some_array.npy')


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Saving and Loading Text Files, vamos a ver un ejemplo de cargar texto en un array

In [34]:
#Generamos el texto 
!cat array_ex.txt
0.580052,0.186730,1.040717,1.134411
0.194163,-0.636917,-0.938659,0.124094
-0.126410,0.268607,-0.695724,0.047428
-1.484413,0.004176,-0.744203,0.005487
2.302869,0.200131,1.670238,-1.881090
-0.193230,1.047233,0.482803,0.960334

cat: array_ex.txt: No existe el fichero o el directorio


(-0.19323, 1.047233, 0.482803, 0.960334)

In [36]:
#Se carga el fichero
arr = np.loadtxt('array_ex.txt', delimiter=',')

IOError: [Errno 2] No such file or directory: 'array_ex.txt'

Linear Algebra
El Algebra lineal es una parte importante de la libraría numpy

In [37]:
# Generamos 2 array
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [38]:
# Se puede usar el método dot en vez de la función dot, para multiplicar matrices
x.dot(y)


array([[  28.,   64.],
       [  67.,  181.]])

In [39]:
# La librerías linalg tiene la pricipales funciones para descomposición de matrices
from numpy.linalg import inv, qr

In [44]:
# Generamos una array bidimensional 3 x 3 y calculamos la multiplicación de ella por la transpuesta
X = randn(3, 3)
mat = X.T.dot(X)
mat

array([[ 3.22488754, -1.14718875, -0.19520316],
       [-1.14718875,  0.47634667,  0.14278529],
       [-0.19520316,  0.14278529,  0.80386645]])

In [45]:
inv(mat)

array([[  2.30912421,   5.69628634,  -0.45106691],
       [  5.69628634,  16.26931154,  -1.50657524],
       [ -0.45106691,  -1.50657524,   1.40205764]])

In [46]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   1.49880108e-15,  -5.55111512e-17],
       [  3.19189120e-16,   1.00000000e+00,   2.77555756e-17],
       [  0.00000000e+00,   2.22044605e-16,   1.00000000e+00]])

In [47]:
q, r = qr(mat)

In [48]:
q

array([[-0.94063445, -0.26338532, -0.21409109],
       [ 0.33461175, -0.61376716, -0.71506982],
       [ 0.05693681, -0.74425671,  0.66546236]])

In [49]:
r

array([[-3.42841741,  1.24660619,  0.27716205],
       [ 0.        , -0.09648218, -0.63450627],
       [ 0.        ,  0.        ,  0.47463267]])

Random Number Generation
La biblioteca np.random tiene varias funciones que nos permite generar números aleatorios, de manera más eficicente que con python



In [4]:
#Generar muchos números aleatorios
samples = np.random.normal(size=(4, 4))
samples

array([[-0.66056606,  0.36507509, -0.15979168,  1.22689436],
       [-0.58574083, -0.9370171 ,  0.16387519, -1.21714519],
       [ 0.46083778, -0.34378016,  0.5899879 , -1.64651888],
       [-1.09066808, -0.72217499,  0.03942625, -0.76637736]])